# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Build Docker container
    init: docker-compose build
    command: docker-compose up -d
  - name: Install local testing harness 
    init: cd app; poetry install
